TRAINING_DATA = [
    ("My payment failed and I was charged twice", "billing", "high"),
    ("I need a refund for my last invoice", "billing", "high"),
    ("Why was my credit card declined?", "billing", "high"),
    ("I cannot complete checkout, payment error", "billing", "high"),
    ("Incorrect amount charged on my account", "billing", "high"),
    ("I want to cancel my subscription and get a refund", "billing", "medium"),
    ("Invoice not received for last month", "billing", "medium"),
    ("How do I update my billing address?", "billing", "low"),
    ("Can I switch from monthly to annual plan?", "billing", "low"),
    ("Where can I download my receipts?", "billing", "low"),

    ("I cannot log into my account", "authentication", "high"),
    ("My password reset email never arrived", "authentication", "high"),
    ("Account locked after too many attempts", "authentication", "high"),
    ("Two factor authentication is not working", "authentication", "high"),
    ("I lost access to my authenticator app", "authentication", "high"),
    ("Login page shows an error every time", "authentication", "high"),
    ("How do I enable single sign on?", "authentication", "medium"),
    ("Can I change my username?", "authentication", "low"),
    ("How do I set up Google login?", "authentication", "low"),
    ("Session keeps expiring too quickly", "authentication", "medium"),

    ("I have not received my salary this month", "hr", "critical"),
    ("My payslip shows wrong deductions", "hr", "high"),
    ("I need to apply for parental leave", "hr", "medium"),
    ("How many vacation days do I have left?", "hr", "low"),
    ("I want to update my emergency contact", "hr", "low"),
    ("Performance review process questions", "hr", "low"),
    ("Onboarding documents not received", "hr", "medium"),
    ("I need a letter of employment", "hr", "medium"),
    ("Expense reimbursement not processed", "hr", "high"),
    ("Health insurance coverage question", "hr", "medium"),

    ("The app crashes every time I open it", "technical", "critical"),
    ("Getting a 500 internal server error", "technical", "high"),
    ("Dashboard is not loading any data", "technical", "high"),
    ("Export to CSV feature is broken", "technical", "high"),
    ("API returning wrong response format", "technical", "high"),
    ("Mobile app stuck on loading screen", "technical", "high"),
    ("Search results are not accurate", "technical", "medium"),
    ("Notifications are not being delivered", "technical", "medium"),
    ("Dark mode is not saving my preference", "technical", "low"),
    ("How do I use the bulk import feature?", "technical", "low"),
]